version: '3'

services:

  service_1.php:
    container_name: service_1.php
    hostname: service_1.php
    build: .
    networks:
      - proxy_services.network
    volumes:
      - ./:/var/www/service_1

networks:
  proxy_services.network:
    external: true