version: '3'

services:

  service_2.php:
    container_name: service_2.php
    build: .
    networks:
      - proxy_services.network
    volumes:
      - ./:/var/www/service_2

networks:
  proxy_services.network:
    external: true